### ISSUE TITLE
En masse opgaver virker pludseligt ikke.....

### ISSUE THREAD

**Issue by algorythm** [awo-dev/dtu_prog_opgaver_s1#1]
Opgave 5, 11, 12 ,13 er begyndt at crashe hver gang man kører den. Jeg aner ikke hvorfor.

Det er sket efter 5c406ab7cca873a049575257879621c84646a580, 8e4f957ee014882f53725b912446bc56dfb32815, 623a2aed678489db35ddcb651849ec410a8f72f0 eller f38c6263f73ab8868ab640f0bde0c62a3261d544........

Jeg får følgende compiler-fejl:

```
Exception in thread "main" java.util.NoSuchElementException
    at java.util.Scanner.throwFor(Scanner.java:862)
    at java.util.Scanner.next(Scanner.java:1485)
    at java.util.Scanner.nextDouble(Scanner.java:2413)
    at Uge2.opg5(Uge2.java:21)
    at App.main(App.java:52)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by algorythm** [comment]
Der er nok stor sandsynlighed for at det er det sidste commit (f38c6263f73ab8868ab640f0bde0c62a3261d544) siden det var det eneste sted jeg har rettet i de klasser der nu ikke virker (Uge2 og Uge3).

Hvis jeg fjerner 

``` java
while(true)
{
   // ...
}
```

Så virker opgave 13 næsten (den får ikke spurgt om hvor mange lag der skal være - altså den springer `in.nextLine();` over)

Fuck java.

Formentligt et problem med Scanneren
